[tool.poetry]
name = "workstation-cli"
version = "0.1.0"
description = "Python lib for my personal workstation setup"
authors = ["Victor Mazzeo <victor.mazzeo@groupeseloger.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/militu/workstation-cli"
repository = "https://github.com/militu/workstation-cli"
documentation = "https://militu.github.io/workstation-cli"

packages = [
    { include = "workstation", from = "src" },
]

[tool.poetry.urls]
Changelog = "https://github.com/militu/workstation-cli/releases"

[tool.poetry.dependencies]
python = "^3.8"
loguru = "0.5.3"
click = "^8.0.3"
distro = "^1.6.0"
wget = "^3.2"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.4.3"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
pep8-naming = "^0.12.0"
darglint = "^1.8.0"
reorder-python-imports = "^2.5.0"
pre-commit = "^2.13.0"
pre-commit-hooks = "^4.0.1"
black = "^21.9b0"
Pygments = "^2.9.0"
mkdocs-minify-plugin = "^0.5.0"
mkdocs-redirects = "^1.0.3"
mkdocs-material = "^8.0.4"
mkdocs-macros-plugin = "^0.6.0"
commitizen = "^2.19.0"
python-semantic-release = "^7.23.0"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:tool.poetry.version"
]
branch = "master"
build_command = false
commit_message = "[skip ci] Releasing {version}"
upload_to_repository = false

[tool.poetry.scripts]
install-workstation = "workstation.cli:install_workstation"



[build-system]
requires = ["poetry-core>=1.1.7"]
build-backend = "poetry.core.masonry.api"
