[project]
name = "coreml_pytorch_utils"
version = "0.1.1"
description = "Coreml utils that helps export pytorch based models"
dependencies = [ "coremltools>=5.0", "future",]
requires-python = ">=3.9"
[[project.authors]]
name = "machineko"
email = "machineko@protonmail.com"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "EUPL-1.2"

[project.urls]
homepage = "https://github.com/machineko/coreml_torch_utils"

[project.optional-dependencies]

[tool.pdm.dev-dependencies]
test = [ "pytest", "torch==1.10.1", "pytest-cov", "nox",]
lint = [ "black",]
docs = [ "mkdocs", "mkdocs-material",]
