[tool.poetry]
name = "uboxadmin"
version = "0.1.0"
description = ""
authors = ["heweitao <675428202@qq.com>"]

[[tool.poetry.source]]
name = "privacy"
url = "http://192.168.1.92:8080/"

[tool.poetry.dependencies]
python = "^3.6"
Django = "^1.11.8"
djangorestframework = "3.11.2"
djangorestframework-simplejwt = "4.3.0"
typing-extensions = "^3.10.0"
djangorestframework-camel-case = "^1.2.0"
captcha = "^0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-django = "*"
flake8 = "*"
black = "*"
isort = "^5.8.0"
Faker = "^8.1.3"
coverage = "^5.5"
django-seed = "^0.2.2"
bpython = "^0.21"
django-extensions = "2.2.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py36']
exclude = ["*/migrations/*"]
