[tool.poetry]
name = "sug"
version = "0.1.0"
description = "A generator for systemd unit files"
authors = ["4thel00z <4thel00z@gmail.com>"]
license = "GPL-3"
readme = "README.md"
homepage = "https://github.com/4thel00z/sug"
packages = [
    { include = "sug" }
]

[tool.poetry.dependencies]
python = "^3.5"
typer = "^0.4.0"

[tool.poetry.scripts]
sug = 'sug.__main__:app'



[tool.poetry.dev-dependencies]
neovim = "^0.3.1"
black = "^21.12b0"
ptpython = "^3.0.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
