
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-23T03:04:10+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "ffb307f884c9ea8a43a8e69e8ce4cad3107fd5c3",
 "version": "v2.1.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
