name: unit tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: run unit tests using tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
        tox --skip-missing-interpreters=true
