name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run setup.py
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        rm -fr dist
        python setup.py bdist_wheel sdist
    - name: Save AUTHORS and ChangeLog
      uses: actions/upload-artifact@v2
      with:
        name: acl-output
        path: |
          AUTHORS
          ChangeLog

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.2.2
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}

  update_acl:
      name: update AUTHORS and ChangeLog
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - uses: actions/checkout@v2
          with:
            ref: main
        - name: Download AUTHORS and ChangeLog
          uses: actions/download-artifact@v2
          with:
            name: acl-output
        - name: update
          run: |
            git add AUTHORS ChangeLog
            if [[ ! -z $(git status -s AUTHORS ChangeLog) ]]
            then
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git commit -m 'Update project metadata' AUTHORS ChangeLog
             git push
            fi
