name: Docs
# on: [push, release]

jobs:
  notebooks:
    name: "Build the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python and Rust
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install libopus-dev
        run: |
          sudo apt-get update
          sudo apt-get -y install libopus-dev

      - name: Install toolchain
        id: tc
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      # - uses: messense/maturin-action@v1
      #   with:
      #     maturin-version: latest
      #     command: develop
      - name: Maturin
        run: |
          python -m pip install maturin
          python -m venv venv
          source venv/bin/activate
          maturin develop

      - name: Install doc dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r docs/requirements.txt

      - uses: actions/upload-artifact@v2
        with:
          name: so-for-${{ github.sha }}
          path: songbird

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}