[tool.poetry]
name = "rhizo-widgets"
version = "0.1.4"
description = ""
authors = ["Andy Jefferson <andy@rhizo.co>"]

[tool.poetry.dependencies]
python = "^3.6"
ipywidgets = "^7.6.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
