valid_file_formats:
  - cbin
  - wav

required_extract_todo_list_keys:
  - bird_ID
  - file_format
  - !!python/tuple [data_dirs, annotation_file]
  - output_dir
  - labels_to_use

optional_extract_todo_list_keys:
  - spect_params
  - segment_params
  - feature_group
  - feature_list

valid_models:
  sklearn:
    - knn
    - svm
  keras:
    - flatwindow

valid_model_keys:
  knn:
    - feature_list_indices
    - feature_group
    - hyperparameters
    - predict_proba

  svm:
    - feature_list_indices
    - feature_group
    - hyperparameters
    - predict_proba

  flatwindow:
    - neuralnet_input
    - hyperparameters

hyperparameters:
# key is hyperparam. name, value is valid type
  knn:
    k: int

  svm:
    C: !!python/tuple [int, float]
    gamma: !!python/tuple [int, float]

  flatwindow:
    epochs: int
    batch_size: int

required_predict_todo_list_keys:
  - file_format
  - !!python/tuple [data_dirs, annotation_file]
  - output_dir
  - model_meta_file

optional_predict_todo_list_keys:
  - bird_ID
  - convert
  - predict_proba

valid_convert_types:
  - notmat

must_train_with_prob_true:
  - svm
