[tool.poetry]
name = "LogHelper"
version = "1.00.02"
description = "日志助手，支持多进程，支持json格式，支持flask"
readme = "README.md"
authors = ["ITXiaoPang <itxiaopang.djh@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
python-json-logger = {version = "^2.0", optional = true}
concurrent-log = {version = "^1.0", optional = true}
Flask = {version = "^2.0", optional = true}

[tool.poetry.extras]
json = ["python-json-logger"]
flask = ["Flask"]
concurrent = ["concurrent-log"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
