
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-25T14:16:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1adcf2f63c3a226a2eeb030f15d56ee5f87b0e8",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
