[tool.poetry]
name = "graphql-core"
version = "3.0.6"
description = """
GraphQL-core is a Python port of GraphQL.js,
 the JavaScript reference implementation for GraphQL."""
license = "MIT"
authors = [
    "Christoph Zwerschke <cito@online.de>"
]
readme = "README.md"
homepage = "https://github.com/graphql-python/graphql-core"
repository = "https://github.com/graphql-python/graphql-core"
documentation = "https://graphql-core-3.readthedocs.io/"
keywords = ["graphql"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
packages = [
    { include = "graphql", from = "src" },
    { include = "tests", format = "sdist" },
    { include = "docs", format = "sdist" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-asyncio = ">=0.16,<1"
pytest-benchmark = "^3.4"
pytest-cov = "^3.0"
pytest-describe = "^2.0"
black = [
    {version = "21.12b0", python = ">=3.6.2"},
    {version = "20.8b1", python = "<3.6.2"}
]
flake8 = "^4.0"
mypy = "0.930"
sphinx = "^2.4"
sphinx_rtd_theme = ">=0.4,<1"
check-manifest = "0.40"
bump2version = ">=1.0,<2"
tox = "^3.24"

[tool.black]
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']

[build-system]
requires = ["poetry>=1,<2"]
build-backend = "poetry.masonry.api"
