[tool.poetry]
name = "havi"
version = "0.1.1"
description = "perform bayesian inference over physical models"
authors = ["bjornaer <maxemijo@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Science/Research',
    'Topic :: Scientific/Engineering :: Physics',
    'License :: OSI Approved :: Apache Software License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
]
packages = [{include="havi"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21.5"
torch = "^1.10.1"
pyro-ppl = "^1.8.0"
pandas = "^1.3.5"
seaborn = "^0.11.2"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
