[tool.poetry]
name = "async_eval"
version = "0.1.6"
description = "eval async code from sync"
authors = ["Yurii Karabas <1998uriyyo@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/uriyyo/async-eval"

[tool.poetry.dependencies]
python = "^3.6.1"
nest-asyncio = "^1.5.4"
pydevd-pycharm = { version = ">=212.5080.18,<214.0.0", optional = true }
trio = { version = "^0.19.0", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"
pre-commit = "^2.16.0"

[tool.poetry.extras]
pydevd-pycharm = ["pydevd-pycharm"]
trio = ["trio"]
all = ["pydevd-pycharm", "trio"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''
