
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-22T20:06:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f20885a8a4fdf525672cd3d4c1f99eec10adaf90",
 "version": "5.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
