


__version__ = "0.2021.12.27"



from .MediaWikiLocalSettingsArrayAppend import MediaWikiLocalSettingsArrayAppend
from .MediaWikiLocalSettingsComplexVariableAssignment import MediaWikiLocalSettingsComplexVariableAssignment
from .MediaWikiLocalSettingsVariableAssignment import MediaWikiLocalSettingsVariableAssignment
from .MediaWikiLocalSettingsFile import MediaWikiLocalSettingsFile

