
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-23T01:31:42+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbec4eb4e41397d04d0ec0523623b13b5aa01bb1",
 "version": "v2.1.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
