[tool.poetry]
name = "etosdk"
version = "0.2"
description = "Eto Labs Python SDK"
authors = ["Eto Devs <devs@eto.ai>"]
packages = [{ include = "eto" }]

[tool.poetry.dependencies]
python = "^3.9"
python-dateutil = "^2.8.2"
urllib3 = "^1.26.7"
rikai = "^0.0.14"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
pytest = "^6.2.5"
pylint = "^2.11.1"
isort = "^5.10.1"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
