# Generated by Django 2.0.10 on 2019-01-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20180607_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Ordning'),
        ),
    ]
