# Generated by Django 2.0.10 on 2019-01-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_auto_20190114_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner url'),
        ),
    ]
