# Generated by Django 4.0 on 2021-12-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0011_alter_banner_position_bannerviews_bannertotalclicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Banner MOBILE 320x320'),
        ),
        migrations.AddField(
            model_name='banner',
            name='small_mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Banner MOBILE 300x250'),
        ),
    ]
