[tool.poetry]
name = "miniature-lighting-desk"
version = "0.1.0"
description = "Desk software for Miniature Lighting Controller"
authors = ["John Maximilian <2e0byo@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pyusb = "^1.2.1"
coloredlogs = "^15.0.1"
autobahn = {extras = ["serialization"], version = "^21.11.1"}
click = "^8.0.3"

[tool.poetry.scripts]
lighting_desk = "miniature_lighting_desk.cli:cli"

[tool.poetry.dev-dependencies]
devtools = "^0.8.0"
mkdocs = "^1.2.3"
mkdocs-material = "^8.1.3"
pytest = "^6.2.5"
pytest-sugar = "^0.9.4"
pytest-mock = "^3.6.1"
pytest-asyncio = "^0.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
