[tool.poetry]
name = "mystit"
version = "0.1.0"
description = "A MarkdownIt-Py preconfigured for Myst syntax"
authors = ["Axel H. <noirbizarre@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
PyYAML = "^6.0"
blinker = "^1.4"
markdown-it-py = {extras = ["linkify", "plugins"], version = "^2.0.0"}
mdit-py-plugins = "^0.3"
Pygments = {version = "^2.10.0", optional = true}

# [tool.poetry.group.lint.dependencies]
black = {version = "^21.12b0", allow-prereleases = true, optional = true}
flake8 = {version = "<4.0", optional = true}
isort = {version = "^5.10.1", optional = true}
mypy = {version = "^0.920", optional = true}
types-mock = {version = "^4.0.4", optional = true}

# [tool.poetry.group.test.dependencies]
pyquery = {version = "^1.4.3", optional = true}
pytest = {version = "^6.2.5", optional = true}
pytest-cov = {version = "^3.0.0", optional = true}
pytest-pythonpath = {version = "^0.7.3", optional = true}
pytest-sugar = {version = "^0.9.4", optional = true}
pytest-mock = {version = "^3.6.1", optional = true}


[tool.poetry.extras]
pygments = [
    "pygments",
]
test = [
  "pyquery",
  "pytest",
  "pytest-cov",
  "pytest-pythonpath",
  "pytest-sugar",
]
lint = [
  "black",
  "flake8",
  "isort",
  "mypy",
  "types-mock",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
# Maintain compatibility with Black
profile = "black"
multi_line_output = 3

# Sort imports within their section independent of the import type
force_sort_within_sections = true

# Designate "pelican" as separate import section
known_markdownit = "markdown_it,mdit_py_plugins"
known_pygments = "pygments"
known_tests = "pytest,pyquery"
sections = "FUTURE,STDLIB,THIRDPARTY,MARKDOWNIT,PYGMENTS,TESTS,FIRSTPARTY,LOCALFOLDER"

[tool.pytest.ini_options]
norecursedirs = ".git build dist"
testpaths = "tests"
