model_selection: # list of dictionaries, dash without key next to is a list item so each dictionary is an item in the list
  spect_params :
      samp_freq : 32000 # Hz
      window_size : 512
      window_step : 32
      freq_cutoffs : [1000,8000]

  num_replicates: 5
  num_samples:
    start : 100
    stop : 1000
    step : 100

  models:
    - {model: knn, feature_group: knn}
    - {model: svm, feture_group: svm}

  todo_list:
    -
      bird_ID : gr41rd51

      data_dirs:
        - C:\DATA\gr41rd51\pre_surgery_baseline\06-21-12
        - C:\DATA\gr41rd51\pre_surgery_baseline\06-19-12
        - C:\DATA\gr41rd51\pre_surgery_baseline\06-20-12
        - C:\DATA\gr41rd51\pre_surgery_baseline\06-22-12

      output_dir: C:\DATA\gr41rd51\

      labelset : iabcdefgjkm

    - #2
      bird_ID : bl26lb16

      data_dirs:
        - C:\DATA\bl26lb16\pre_surgery_baseline\041912
        - C:\DATA\bl26lb16\pre_surgery_baseline\042012

      output_dir: C:\DATA\bl26lb16\

      labelset : iabcdef

    - #3
      bird_ID : gy6or6

      data_dirs:
        - C:\DATA\gy6or6\032412
        - C:\DATA\gy6or6\032212
        - C:\DATA\gy6or6\032312
        - C:\DATA\gy6or6\032512

      output_dir: C:\DATA\gy6or6\

      labelset : iabcdefghjk

    - #4
      bird_ID : or60yw70

      data_dirs:
        - C:\DATA\or60yw70\baseline\09-29-12
        - C:\DATA\or60yw70\baseline\09-27-12
        - C:\DATA\or60yw70\baseline\09-28-12
        - C:\DATA\or60yw70\baseline\09-30-12

      output_dir: C:\DATA\or60yw70\

      labelset : iabcdefg