extract:
  spect_params:
    samp_freq: 32000 # Hz
    nperseg: 512
    noverlap: 480
    freq_cutoffs: [1000,8000]
  segment_params:
    threshold: 5000 # arbitrary units of amplitude
    min_syl_dur: 0.02 # ms
    min_silent_dur: 0.002 # ms

  todo_list:
    - #1
      bird_ID : bl26lb16

      file_format: evtaf

      data_dirs:
        - C:\DATA\bl26lb16\041912
        - C:\DATA\bl26lb16\042012

      feature_group:
        - knn
        - svm

      output_dir: C:\DATA\bl26lb16\

      labelset: iabcdef

    - #2
      bird_ID: gy6or6

      file_format: evtaf

      data_dirs:
        - C:\DATA\gy6or6\032412
        - C:\DATA\gy6or6\032212
        - C:\DATA\gy6or6\032312
        - C:\DATA\gy6or6\032512

      feature_group:
        - knn
        - svm

      output_dir: C:\DATA\gy6or6\

      labelset: iabcdefghjk