predict:
  todo_list:
    - #1
      bird_ID: gy6or6
      model_file : C:\Users\Seymour Snyder\AppData\Local\Temp\pytest-of-Seymour Snyder\pytest-80\tmp_output_dir0\select_output_170914_095043\knn_k4\knn_100samples_replicate0
      file_format: evtaf
      data_dirs:
        - C:\Users\Seymour Snyder\Documents\pyWorkspace\hvc_venv\hybrid-vocal-classifier\tests\test_data\cbins\gy6or6\032312
        - C:\Users\Seymour Snyder\Documents\pyWorkspace\hvc_venv\hybrid-vocal-classifier\tests\test_data\cbins\gy6or6\032412
      output_dir: C:\Data\gy6gy6\