extract:
  spect_params:
    ref: tachibana

  todo_list:
    - #2
      bird_ID : bl26lb16

      file_format: evtaf

      segment_params:
        threshold: 1000 # arbitrary units of amplitude
        min_syl_dur: 0.02 # ms
        min_silent_dur: 0.004 # ms

      feature_group:
        - knn
        - svm

      feature_list:
        - flatwindow

      data_dirs:
        - C:\DATA\bl26lb16\041912
        - C:\DATA\bl26lb16\042012
        - C:\DATA\bl26lb16\042112

      output_dir: C:\DATA\bl26lb16\

      labelset: iabcdef

    - #3
      bird_ID: gy6or6

      file_format: evtaf

      segment_params:
        threshold: 1500 # arbitrary units of amplitude
        min_syl_dur: 0.01 # ms
        min_silent_dur: 0.006 # ms

      feature_group:
        - knn
        - svm

      feature_list:
        - flatwindow

      data_dirs:
        - C:\DATA\gy6or6\032212
        - C:\DATA\gy6or6\032412
        - C:\DATA\gy6or6\032312
        - C:\DATA\gy6or6\032512

      output_dir: C:\DATA\gy6or6\

      labelset: iabcdefghjk