name: lstio
channels:
  - default
dependencies:
  - astropy>=4.2
  - python=3.8 # nail the python version, so conda does not try upgrading / dowgrading
  - conda-forge::ctapipe=0.11
  - conda-forge::eventio
  - conda-forge::corsikaio
  - conda-forge::protozfits=2.0
  - traitlets=5.0 # remove when upgrading to ctapipe > 0.11
  - zeromq
  - ipython
  - numba
  - numpy>=1.18
  - numpydoc
  - pytest
  - pyyaml
  - zlib
  - pip
  - h5py
  - pip:
      - pytest_runner
