[tool.poetry]
name = "ddv-settings"
version = "0.1.1"
description = "Module for easily reading and exporting settings from files"
authors = ["Davide Vitelaru <davide@vitelaru.com>"]
packages = [
  { include = "ddv", from="src"}
]
license = "Unlicense"
readme = "README.md"
keywords = ["ddv", "settings", "ini", "config", "read", "export"]
repository = "https://gitlab.com/davidevi/ddv-settings"

[tool.poetry.dependencies]
python = "^3.9"
configparser = "^5.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
