name: nr.caching
version: 0.4.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
license: MIT
description: A simple key-value caching API with default implementations for an SQLite3
  storage backend and a JSON convenience layer.
requirements:
- python ^3.6
- overrides ^3.1.0
typed: true
test-drivers:
- type: mypy
