# -*- coding: utf-8 -*-

"""
zypev1

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from tests.http_response_catcher import HttpResponseCatcher
from zypev1.api_helper import APIHelper
from zypev1.controllers.video_favorites_controller import VideoFavoritesController


class VideoFavoritesControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(VideoFavoritesControllerTests, cls).setUpClass()
        cls.response_catcher = HttpResponseCatcher()
        cls.controller = VideoFavoritesController(cls.config, cls.response_catcher)

    # Testcase for testing endpoint Delete Video Favorite
    def test_delete_video_favorite_1(self):
        # Parameters for the API call
        consumer_id = '5466584169702d4d300d0000'
        video_id = '56d7594a8f7aca08aabbc8e3'

        # Perform the API call through the SDK function
        self.controller.consumers_video_favorites_by_consumer_id_and_video_id_delete(consumer_id, video_id)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 204)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))


