# -*- coding: utf-8 -*-

"""
zypev1

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from tests.http_response_catcher import HttpResponseCatcher
from zypev1.api_helper import APIHelper
from zypev1.controllers.video_content_rules_controller import VideoContentRulesController


class VideoContentRulesControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(VideoContentRulesControllerTests, cls).setUpClass()
        cls.response_catcher = HttpResponseCatcher()
        cls.controller = VideoContentRulesController(cls.config, cls.response_catcher)

    # Testcase for testing endpoint Delete Video Content Rule
    def test_delete_video_content_rule_1(self):
        # Parameters for the API call
        video_id = '554bfc3e69702d070ef65900'
        id = '5389352e69702d401b000000'

        # Perform the API call through the SDK function
        self.controller.videos_content_rules_by_video_id_and_id_delete(video_id, id)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 204)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))


