# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-01 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboxadmin', '0002_auto_20210521_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
