# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboxadmin', '0004_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_v',
            field=models.IntegerField(default=1, help_text='作用是改完密码，让原来的token失效', max_length=255, verbose_name='密码版本'),
        ),
    ]
