# Generated by Django 2.0.5 on 2018-06-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20180523_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='code',
            field=models.TextField(blank=True, default='', verbose_name='Koden'),
        ),
    ]
