# Generated by Django 2.0.10 on 2019-01-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_auto_20190114_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
        ),
    ]
