# Generated by Django 2.0.10 on 2019-01-15 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_banner_code_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='valid_until',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Giltig till'),
        ),
    ]
