
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-21T07:19:55-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e182fdd14c08e8ac41d066ba16123e52a00de58f",
 "version": "v1.1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
