[build-system]
requires = [
	"wheel", "setuptools",
	"chardet",
	"lazy-object-proxy",
	"lxml",
	"pathspec",
	"tree-sitter~=0.19.0",
	"snakeoil~=0.9.6",
	"pkgcore~=0.12.8",
]
build-backend = "setuptools.build_meta"
