[tool.poetry]
name = "nv-utils"
version = "0.2.0"
description = "Parsers, formatters, data structures and helpers for Python 3 (>=3.9)"
authors = ["Gustavo Santos <gustavo@next.ventures>"]
license = "MIT"
repository = "https://github.com/gstos/nv-utils"
packages = [{ include = "nv"}]
# New attributes
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.9"
openpyxl = { version = "^3.0.5", optional = true }
xlrd = { version = "^2.0.1", optional = true }
xlwt = { version = "^1.3.0", optional = true }
pytz = "^2021.1"
msgpack-python = { version = "^0.5.6", optional = true }
xmltodict = { version = "^0.12.0", optional = true }
dicttoxml = { version = "^1.7.4", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
PyYAML = "^5.3.1"

[tool.poetry.extras]
xls = ["xlrd", "xlwt"]
xlsx = ["openpyxl"]
pytz = ["pytz"]
msgpack = ["msgpack-python"]
xml = ["xmltodict", "dicttoxml"]
all = ["xlrd", "xlwt", "openpyxl", "msgpack-python", "pytz", "xmltodict", "dicttoxml"]

[tool.pytest.ini_options]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
