[tool.poetry]
name = "utils-upload"
version = "0.1.0"
description = ""
authors = ["Hillo232 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pkg-upload = "^0.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
