
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-22T10:05:43-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e1112e8a18db734c3baeb28caf8a2acc4348fd5",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
