[tool.poetry]
name = "deps_helper"
version = "0.1.1"
description = "dependencies helper"
authors = ["jason"]
readme = "README.md"
keywords = ["dependecy"]
include = ["LICENSE"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
