# Generated by Django 2.0.10 on 2019-01-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_banner_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Bild url'),
        ),
    ]
