# Generated by Django 2.0.10 on 2019-01-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_banner_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='code_mobile',
            field=models.TextField(blank=True, default='', verbose_name='Koden - mobilen'),
        ),
    ]
