[tool.poetry]
name = "chessplotlib"
version = "0.1.0"
description = ""
authors = ["Michael Krumdick <mrkrumdick@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
chess = "^1.8.0"
matplotlib = "^3.5.1"
numpy = "^1.21.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
