# -*- coding: utf-8 -*-

"""
zypev1

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from zypev1.models.ad_tag_3 import AdTag3


class AdTagRequest(object):

    """Implementation of the 'AdTagRequest' model.

    TODO: type model description here.

    Attributes:
        ad_tag (AdTag3): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ad_tag": 'ad_tag'
    }

    def __init__(self,
                 ad_tag=None):
        """Constructor for the AdTagRequest class"""

        # Initialize members of the class
        self.ad_tag = ad_tag

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        ad_tag = AdTag3.from_dictionary(dictionary.get('ad_tag')) if dictionary.get('ad_tag') else None

        # Return an object of this model
        return cls(ad_tag)
