################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 5 - Production/Stable",
		"License :: OSI Approved :: Apache Software License",
		"Programming Language :: Python :: 3",
	],
	description = "This python module provides OS licenses. This module is intended as a building block in module/package/application management.",
	include_package_data = True,
	install_requires = [
	],
	keywords = [
		"license",
	],
	license = "Apache2",
	name = "jk_licenses",
	package_data = {
		"": [
			"licenses/*",
		],
	},
	packages = [
		"jk_licenses",
	],
	version = "0.2021.12.30",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
