
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-23T02:24:17+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "a78deae79fbca36efd94a1269291b305022a1b46",
 "version": "v2.1.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
