[project]
name = "MAGOT2"
version = "2.0.0beta"
description = "New, simpler toolkit for random common genomic analyses"


[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"
