# Generated by Django 2.0.5 on 2018-05-23 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicerat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Banner')),
                ('position', models.CharField(choices=[('FR', 'Top'), ('SO', 'Sidebar'), ('JR', 'Content'), ('SR', 'Bottom')], default='FR', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-created'],
            },
        ),
    ]
