# Generated by Django 2.0.5 on 2018-05-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='code',
            field=models.TextField(blank=True, default='', verbose_name='Undertitel'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('TOP', 'Top'), ('SDB', 'Sidebar'), ('CON', 'Content'), ('BOT', 'Bottom')], default='TOP', max_length=3),
        ),
    ]
