# -*- coding: utf-8 -*-

"""
zypev1

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ViewRelationsipsResponse(object):

    """Implementation of the 'View Relationsips response' model.

    TODO: type model description here.

    Attributes:
        playlists (list of object): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "playlists": 'playlists'
    }

    def __init__(self,
                 playlists=None):
        """Constructor for the ViewRelationsipsResponse class"""

        # Initialize members of the class
        self.playlists = playlists

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        playlists = dictionary.get('playlists')

        # Return an object of this model
        return cls(playlists)
