dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  url: ftp://guest:GU.205dldo@ftp.softronics.ch/mvtec_anomaly_detection/mvtec_anomaly_detection.tar.xz
  category: leather
  task: segmentation
  label_format: None
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  inference_batch_size: 32
  num_workers: 36

model:
  name: stfpm
  backbone: resnet18
  layers:
    - layer1
    - layer2
    - layer3
  lr: 0.4
  momentum: 0.9
  weight_decay: 0.0001
  early_stopping:
    patience: 3
    metric: pixel_AUROC
    mode: max
  normalize_scores: false
  threshold:
    image_default: 0
    pixel_default: 0
    adaptive: true

project:
  seed: 0
  path: ./results
  log_images_to: [local]
  logger: false
  save_to_csv: false

optimization:
  compression:
    apply: false
  nncf:
    apply: false
    input_info:
      sample_size: null
    compression:
      algorithm: quantization
      initializer:
        range:
          num_init_samples: 256
    update_config:
      init_weights: snapshot.ckpt
      hyperparameter_search:
        parameters:
          lr:
            min: 1e-4
            max: 1e-2

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: null
  accumulate_grad_batches: 1
  amp_backend: native
  amp_level: O2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 2
  checkpoint_callback: true
  default_root_dir: null
  deterministic: true
  distributed_backend: null
  fast_dev_run: false
  flush_logs_every_n_steps: 100
  gpus: 1
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  max_epochs: 100
  max_steps: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  reload_dataloaders_every_epoch: false
  replace_sampler_ddp: true
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: null
  track_grad_norm: -1
  truncated_bptt_steps: null
  val_check_interval: 1.0
  weights_save_path: null
  weights_summary: top
