[tool.poetry]
authors = ["Joao Corte <jpaulorc@gmail.com>"]
description = "Project created to learning Streamlit."
exclude = ["streamlit_stackoverflow/.git"]
name = "streamlit_stackoverflow"
readme = "README.md"
version = "0.1.2"

[tool.poetry.dependencies]
matplotlib = "^3.5.1"
numpy = "1.21.4"
pandas = "^1.3.5"
plotly = "^5.4.0"
python = ">=3.9,<3.11"
pywaffle = "^0.6.3"
seaborn = "^0.11.2"
streamlit = "^1.2.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
flake8 = "^4.0.1"
ipython = "^7.30.1"
isort = "^5.10.1"
mypy = "^0.920"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
