# Generated by Django 3.2.10 on 2021-12-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0005_index_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='streamblocks',
        ),
    ]
