
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-10T16:43:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "db67c0b064e5fb5527dd267717b91e62b47a4f25",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
