install_requires=[
    'hyperopt==0.2.5',
    'matplotlib==3.3.3',
    'numpy==1.18.5',
    'pandas==1.1.5',
    'requests==2.25.1',
    'scipy==1.4.1',
    'statsmodels==0.12.2',
    'torch==1.8.1+cpu',
    'tqdm==4.54.1',
],