[tool.poetry]
name = "ntn_torch"
version = "0.3.3"
description = "ntn_torch is a library to build n-tuple neural network models using the framework of pytorch"
authors = ["Rafael F. Katopodis <rafaelkatopodis@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6,<3.11"
torch = "^1.10.0"
numpy = "^1.21.4"
stable-baselines3 = {extras = ["extra"], version = "^1.3.0"}
pybullet = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
matplotlib = "^3.5.1"
scikit-learn = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
