[tool.poetry]
name = "async_mixin"
version = "0.0.1"
description = "Boilerplate for an Asynchronous HTTP REST Client as a Mixin"
authors = ["Andrew Rainboldt <arainboldt@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.1"
asyncio-throttle = "^1.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
