[tool.poetry]
name = "sentry_faust_integration"
version = "0.1.3"
description = ""
authors = ["dmitry <dmitrysmirnov931@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
faust = "^1.10.4"
sentry-sdk = "^1.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
