[tool.poetry]
name = "django-fb_phoneauth"
packages = [
    {include = "fb_phoneauth"}
]
version = "0.1.2"
description = "Google Firebase authentication for django applications."
authors = ["prajeeshag <prajeeshag@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.1"
django-phonenumber-field = ">5.0.0"
phonenumbers = "^8.12.38"
firebase-admin = "^5.1.0"

[tool.poetry.dev-dependencies]
selenium = "^4.1.0"
django-dotenv = "^1.4.2"
setuptools = "^59.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
