
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-26T22:02:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e700149e995371ff443dfef91f29f4412e5529f6",
 "version": "5.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
