[tool.poetry]
name = "data-product-definition-tooling"
version = "0.0.1"
description = "Data Product Definition Tooling"
authors = ["Digital Living International Ltd"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/ioxio-nexus/data-product-definition-tooling"
packages = [
    {include="converter", from="."}
]

[tool.poetry.scripts]
converter = "converter.cli:cli"

[tool.poetry.dependencies]
python = ">=3.9.0"
typer = "^0.4.0"
deepdiff = "^5.7.0"
fastapi = "^0.70.1"
stringcase = "^1.2.0"

[tool.poetry.dev-dependencies]
isort = ">=4.3.21"
pytest = "^6.0.1"
pytest-asyncio = "^0.10.0"
flake8 = "^3.8.3"
mypy = "^0.782"
black = {version = "^21.12b0", allow-prereleases = true}
syrupy = "^1.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
