
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-25T13:43:31-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e720870c0928996f8b77a38208106ff0447ccb6",
 "version": "v1.1.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
