[tool.poetry]
name = "nytxw-puz-cli"
version = "1.1.0"
description = "CLI tool to convert NY Times crosswords into Across Lite files (.puz)"
authors = ["Chris Tam <ohgodtamit@gmail.com>"]
repository = "https://github.com/GodTamIt/nytxw-puz-cli"
license = "BSD-2-Clause"
readme = "README.md"

packages = [
    { include = "nytxw_puz" },
    { include = "utils/*.py" },
]

[tool.poetry.dependencies]
python = "^3.7"
colorlog = "^6.6.0"
requests = "^2.26.0"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
black = "*"

[tool.poetry.scripts]
nytxw_puz = "nytxw_puz.main:main"
nytxw_gen = "utils.nytxw_gen:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
