[project]
name = "django-vditor"
version = "1.1.1"
description = "A WYSIWYG editor plugin made by vditor for django"
readme = "README.md"
keywords = [ "django", "editor", "django-application",]
dependencies = [ "django>=2.2",]
requires-python = ">=3.5"
dynamic = [ "classifiers",]
[[project.authors]]
name = "pi-dal"
email = "pi-dal@foxmail.com"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://pypi.org/project/django-vditor"
Repository = "https://github.com/pi-dal/django-vditor"
Documentation = "https://github.com/pi-dal/django-vditor/blob/main/README.md"

[tool.pdm]
includes = [ "vditor/", "README.md",]

[tool.pdm.dev-dependencies]
dev = [ "coverage~=5.4",]
