[tool.poetry]
name = "dmdm"
version = "1.4.5"
description = "Django MarkDown Mails"
authors = ["Guilhem Saurel <guilhem.saurel@laas.fr>"]
license = "BSD-2-Clause"
readme = "README.md"
homepage = "https://github.com/nim65s/dmdm"
repository = "https://github.com/nim65s/dmdm.git"

[tool.poetry.dependencies]
python = "^3.6.2"
mdmail = "^0.1.3"
Django = ">=2.2<5.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.0"
safety = "^1.10.3"
mypy = "^0.812"
django-stubs = "^1.7.0"
pydocstyle = "^6.0.0"
pre-commit = "^2.11.1"
Sphinx = "^3.5.3"
coverage = "^5.5"
myst-parser = "^0.15.1"
types-toml = "^0.10.1"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
