# Generated by Django 2.2.12 on 2020-04-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0009_banner_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='Klicks'),
        ),
        migrations.AddField(
            model_name='banner',
            name='impressions',
            field=models.IntegerField(default=0, verbose_name='Visningar'),
        ),
    ]
