[tool.poetry]
name = "byubit"
version = "0.1.1"
description = "A library for teaching beginners how to program"
authors = ["Gordon Bean <gbean@cs.byu.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
matplotlib = "^3.5.1"
numpy = "^1.21.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
