name: flox-tests
channels:
  - conda-forge
dependencies:
  - cachey
  - codecov
  - dask-core
  - netcdf4
  - pandas
  - pip
  - pytest
  - pytest-cov
  - xarray
  - pre-commit
  - numpy_groupies
  - pooch
  - toolz
  - numba
