
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-24T16:19:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5110d3c2132d7d805825f9a5dfca84ecc1fd2b99",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
