
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-23T14:33:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5efe4d95757b250276fcd9188f5bdd5431c0b3e9",
 "version": "0.10.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
