# Generated by Django 3.1.12 on 2021-07-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationalliancehistory',
            name='alliance_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
