version= 1
disable_existing_loggers= true

[formatters.simple]
format= '%(levelname)s:%(name)s:%(message)s'

[handlers.console]
level= 'DEBUG'
class= 'logging.StreamHandler'
formatter='simple'

[loggers.tgl2rdm]
level='DEBUG'
propagate=true
handlers=['console']

