[tool.poetry]
name = "tgl2rdm"
version = "0.1.4"
description = "Toggl Track to Redmine synchronization util"
authors = ["BANO.notIT <bano.notit@yandex.ru>"]
readme = "README.md"
homepage = "https://github.com/BANOnotIT/tgl2rdm"
classifiers = [
  "Topic :: Internet"
]
keywords = [ "toggl", "redmine", "sync" ]
include = [ "README.md", "tgl2rdm", "config.example.toml", "logger.example.toml" ]

[tool.poetry.scripts]
t2m = "tgl2rdm.__main__:app"

[tool.poetry.dependencies]
python = "^3.7"
typer = {extras = ["all"], version = "^0.3.2"}
toml = "^0.10.2"
petl = "^1.7.4"
schema = "^0.7.4"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
