image: 116944431457.dkr.ecr.eu-west-1.amazonaws.com/data-lake-gitlab-builder:PROD2021Q3

before_script:
  - $(aws ecr get-login --no-include-email --region eu-west-1)
  - export CI_TIMESTAMP=$(date +"%Y-%m-%dT%H-%M-%S")

stages:
  - test

unit-test:
  stage: test
  script:
    - ls
    - bash ci/build-test.sh