[tool.poetry]
name = "pathsingleton"
version = "0.1.0"
description = "Module to track the directory our program starts in."
authors = ["Yashesh Dasari <ydasari@uwaterloo.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
