[tool.black]
line-length = 120
[tool.poetry]
name = "odecloud"
version = "0.13.2"
description = ""
authors = ["Vanielle Lee <vanielle@odecloud.com>"]

[tool.poetry.dependencies]
python = "^3.9"
certifi = "2021.10.8"
charset-normalizer = "2.0.9"
idna = "3.3"
requests = "2.26.0"
urllib3 = "1.26.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
