[tool.poetry]
name = "miniseed2mat"
version = "0.1.2"
description = "Analyzing MiniSEED seismic data in MATLAB"
authors = ["Utpal Kumar <utpalkumar50@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
scipy = "^1.7.3"
obspy = "^1.2.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mseed2mat = "miniseed2mat.main:convertmseed2mat"