[tool.poetry]
name = "omspy"
version = "0.1.5"
description = ""
license = "MIT"
authors = ["Ubermensch <uberdeveloper001@gmail.com>"]
readme = "README.md"
repository = "https://github.com/uberdeveloper/omspy"

[tool.poetry.dependencies]
python = "^3.7"
pendulum = "^2.1.2"
PyYAML = "^6.0"
pydantic = "^1.8.2"

[tool.poetry.group.test.dependencies]
coverage = "^6.0.2"
selenium = "^4.1.0"
pytest = "^6.2.5"
pytest-watch = "^4.2.0"

[tool.poetry.group.brokers.dependencies]
pyotp = "^2.6.0"
kiteconnect = "^4.0.0"
fyers-apiv2 = "^2.0.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
