
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-29T11:49:26-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c59d33a5497bd8ae1f76bc19af2e235b6de7c8e0",
 "version": "14.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
