[tool.bumpver]
current_version = "0.0.5"
version_pattern = "MAJOR.MINOR.PATCH"

[tool.bumpver.file_patterns]
"sudogdz.py" = [
    '__version__ = "{version}"',
]

[build-system]
requires = [
    "flit_core >=3.2,<4",
]
build-backend = "flit_core.buildapi"

[project]
name = "sudogdz"
authors = [{name = "Shishkevich"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Education",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.6"
dependencies = [
    "lxml >=4.7.1",
    "requests >=2.6",
    "beautifulsoup4 >=4.10.0",
    "fake-useragent >=0.1.11",
]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/aye20054925/sudogdz"