# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboxadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='手机'),
        ),
    ]
