# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboxadmin', '0003_auto_20210601_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
