# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-25 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboxadmin', '0006_auto_20210622_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appspaceinfo',
            name='url',
            field=models.CharField(max_length=255, verbose_name='地址'),
        ),
    ]
