[tool.poetry]
name = "pytest-watcher"
version = "0.2.3"
description = "Continiously runs pytest on changes in *.py files"
authors = ["Olzhas Arystanov <o.arystanov@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/olzhasar/pytest-watcher"
repository = "https://github.com/olzhasar/pytest-watcher"
keywords = ["pytest", "watch", "watcher"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Software Development :: Testing",
    "Topic :: Utilities",
]
include = [
    "LICENSE",
]

[tool.poetry.scripts]
pytest-watcher = "pytest_watcher:run"
ptw = "pytest_watcher:run"

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0.0"
watchdog = ">=2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"
black = "^21.9b0"
mypy = "^0.910"
isort = "^5.9.3"
pytest-mock = "^3.6.1"
freezegun = "^1.1.0"
tox = "^3.24.4"
coverage = {extras = ["toml"], version = "^5.5"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
source = ["pytest_watcher"]
omit = ['pytest_watcher/__main__.py']
