
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-21T12:17:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "088c6634741b56d3db44fcc6b9d2081644766c59",
 "version": "2.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
