[dependencies]
ndarray = "0.15.3"
numpy = "0.14.1"

[dependencies.biosphere]
path = "local_dependencies/biosphere"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.14.5"

[lib]
crate-type = ["cdylib"]
name = "biosphere"

[package]
edition = "2018"
name = "biosphere_py"
version = "0.1.0"
[package.metadata.maturin]
name = "biosphere"
