# -*- coding: utf-8 -*-

"""
zypev1

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from tests.http_response_catcher import HttpResponseCatcher
from zypev1.api_helper import APIHelper
from zypev1.controllers.consumers_controller import ConsumersController


class ConsumersControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(ConsumersControllerTests, cls).setUpClass()
        cls.response_catcher = HttpResponseCatcher()
        cls.controller = ConsumersController(cls.config, cls.response_catcher)

    # Testcase for testing endpoint Delete Video Consumer
    def test_delete_video_consumer_1(self):
        # Parameters for the API call
        id = '596d08cc75e3bf0039000002'

        # Perform the API call through the SDK function
        self.controller.consumers_by_id_delete(id)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 204)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = None

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))


