[tool.poetry]
name = "pyobs-fli"
version = "0.15.0"
description = "pyobs module for FLI cameras"
authors = ["Tim-Oliver Husser <thusser@uni-goettingen.de>"]
license = "MIT"
include = ['lib']

[tool.poetry.build]
script = "build.py"
generate-setup-file = false

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
astropy = "^5.0"
numpy = "^1.21"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "Cython>=0.29.0", "numpy>=1.21.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
