[tool.poetry]
name = "rrap"
version = "0.1.2"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7.3"
matplotlib = "^3.0.3"
numpy = "^1.19.1"
joblib = "^0.16.0"
scikit-learn = "^0.23.1"
scipy = "^1.5.2"
sklearn = "^0.0"
threadpoolctl = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
