# Generated by Django 3.2.9 on 2021-12-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFavStock',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remarks')),
                ('red', models.IntegerField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
