# Generated by Django 3.2.10 on 2021-12-25 17:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simpleblog', '0004_auto_20211225_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
