[build-system]
requires = [
    "better-ffmpeg-progress==2.0.2",
    "colorama==0.4.4",
    "decorator==5.1.0",
    "ffmpeg-python==0.2.0",
    "future==0.18.2",
    "pytube==11.0.2",
    "six==1.16.0",
    "tqdm==4.62.3",
    "validators==0.18.2",
    "setuptools==59.2.0"
]
build-backend = "setuptools.build_meta"
