[tool.poetry]
name = "aicp"
version = "0.1.2"
description = ""
authors = ["Tobias Oberrauch <tobias.oberrauch@pioneers.ai>"]
readme = "README.md"

[tool.poetry.scripts]
aicp = "aicp.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.4.0"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
