[tool.poetry]
name = "pgsynthdata"
version = "1.0.1"
description = "Synthetic Data Generator for PostgreSQL"
authors = ["Timon Erhart <timon.erhart@ost.ch>", "Jari Elmer <jari.elmer@ost.ch>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
radar = "^0.3"
click = "^8.0.1"
psycopg2-binary = "^2.9.1"
numpy = "^1.21.2"
toposort = "^1.7"
Faker = "^9.8.0"
prettytable = "^2.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.9b0"
python-dotenv = "^0.19.0"
mypy = "^0.910"
coverage = "^6.1.2"
isort = "^5.10.1"
pylint = "^2.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
disable="C0116, C0115, C0114, C0301, logging-fstring-interpolation"