[tool.poetry]
name = "scalum"
version = "1.1.4"
description = ""
authors = ["Oguz Vuruskaner <ovuruska@outlook.com>"]
packages = [
    { include = "scalum" }
]


[tool.poetry.dependencies]
python = "^3.8"
numpy = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
