[project]
name = "darbiadev-ups"
version = "0.6.0"
description = "darbiadev-ups"
dependencies = [ "requests>=2.26.0", "python-benedict>=0.24.3",]
requires-python = ">=3.10"
[[project.authors]]
name = "Bradley Reynolds"
email = "bradley.reynolds@darbia.dev"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
repository = "https://github.com/darbiadev/darbiadev-ups/"
documentation = "https://darbiadev.github.io/darbiadev-ups/"

[project.optional-dependencies]

[tool.sphinx]
copyright = "Darbia"
author = "Bradley Reynolds"
api_dir = "darbiadev_ups"

[tool.black]
target-version = [ "py310",]
line-length = 120

[tool.pdm.dev-dependencies]
docs = [ "sphinx>=4.3.2", "sphinxcontrib-autoprogram>=0.1.7", "sphinx-rtd-theme>=1.0.0", "toml>=0.10.2",]
tests = [ "pytest>=6.2.5",]

[tool.pytest.ini_options]
addopts = "tests -r a -v --doctest-modules darbiadev_ups"
