
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-27T21:22:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8274bd7d2a77e4af60117ceffdbdd4b64e264f5a",
 "version": "v1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
