[tool.towncrier]
package = "aioredis"
filename = "docs/changelog.md"
directory = "CHANGES/"
start_string = "# Changelog\n"
issue_format = "#{issue}"
underlines = ["", ""]
template = ".towncrier.md.jinja"
title_format = "## {version} - ({project_date})"
