[tool.poetry]
name = "ff_ebook"
version = "0.4.1"
description = "Ebook generator for fanfiction sites."
authors = ["Neia Neutuladh, Michal Hozza"]

[tool.poetry.dependencies]
python = "^3.8"
beautifulsoup4 = "^4.9.1"
requests = "^2.24.0"
cloudscraper = "^1.2.58"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
